Repository safe-global/safe-client-gateway, pull requests merged in 2023-06, with the labels that each got.

#388 Parameterize service configuration
  src/app.module.ts
  src/config/__tests__/test.configuration.module.ts
  src/config/configuration.module.ts
  src/config/entities/__tests__/configuration.ts
  src/datasources/cache/redis.cache.service.spec.ts
  src/routes/balances/balances.controller.spec.ts
  src/routes/cache-hooks/cache-hooks.controller.spec.ts
  src/routes/chains/chains.controller.spec.ts
  src/routes/collectibles/collectibles.controller.spec.ts
  src/routes/contracts/contracts.controller.spec.ts
  src/routes/delegates/delegates.controller.spec.ts
  src/routes/estimations/estimations.controller.spec.ts
  src/routes/flush/flush.controller.spec.ts
  src/routes/messages/messages.controller.spec.ts
  src/routes/notifications/notifications.controller.spec.ts
  src/routes/owners/owners.controller.spec.ts
  src/routes/safe-apps/safe-apps.controller.spec.ts
  src/routes/safes/safes.controller.spec.ts
  src/routes/transactions/__tests__/controllers/add-transaction-confirmations.transactions.controller.spec.ts
  src/routes/transactions/__tests__/controllers/get-transaction-by-id.transactions.controller.spec.ts
  src/routes/transactions/__tests__/controllers/list-incoming-transfers-by-safe.transactions.controller.spec.ts
  src/routes/transactions/__tests__/controllers/list-module-transactions-by-safe.transactions.controller.spec.ts
  src/routes/transactions/__tests__/controllers/list-multisig-transactions-by-safe.transactions.controller.spec.ts
  src/routes/transactions/__tests__/controllers/list-queued-transactions-by-safe.transactions.controller.spec.ts
  src/routes/transactions/__tests__/controllers/preview-transaction.transactions.controller.spec.ts
  src/routes/transactions/__tests__/controllers/propose-transaction.transactions.controller.spec.ts
  src/routes/transactions/transactions-history.controller.spec.ts
Labels: enhancement

#431 fix: always return `rejectors`
  src/routes/transactions/__tests__/controllers/get-transaction-by-id.transactions.controller.spec.ts
  src/routes/transactions/mappers/multisig-transactions/multisig-transaction-details.mapper.ts
Labels: in review

#518 Fix docker compose web container requirement
  docker-compose.yml
Labels: bug
