Repository safe-global/safe-client-gateway, pull requests merged in 2024-04, with the labels that each got.

#1363 Remove `JwtModule` from global scope and validation of its env. vars.
  src/config/configuration.validator.spec.ts
  src/config/configuration.validator.ts
  src/datasources/jwt/jwt.module.ts
Labels: in review

#1436 Fix SwapOrderMapper dependency injection
  src/routes/transactions/mappers/common/swap-order.mapper.ts
Labels: bug

#1439 Rename Order.class to Order.orderClass
  src/routes/transactions/entities/confirmation-view/confirmation-view.entity.ts
  src/routes/transactions/entities/swaps/swap-order-info.entity.ts
  src/routes/transactions/transactions-view.service.ts
Labels: bug

#1474 Use Docker Registry cache backend
  .github/workflows/ci.yml
Labels: github_actions

#1477 Map `TransactionInfo` according to `Transfer['type']`
  src/domain/safe/entities/transfer.entity.ts
  src/routes/transactions/mappers/transfers/transfer-info.mapper.ts
Labels: in review
